### ISSUE TITLE
Flags don't show

### ISSUE THREAD

**Issue by alpha-tango-kilo** [lvella/non-deterministic-minesweeper#1]
Installed using Cargo from GitHub. Tried on Windows and Mac. Unless I'm playing the game wrong, when you right-click a tile it's considered to be flagged, however I don't see this. The tile remains unchanged, however you can't left click on it to reveal it, so I assume it's being flagged okay in the backend, just not displaying correctly.

Let me know if there's any diagnostic information that'd be of use.

Awesome project by the way, really interesting concept that fixes my biggest gripe with Minesweeper!

**Comment by lvella** [comment]
Hi, this is most likely because it couldn't find the file `resources/flags.svg` as I haven't yet figured out the proper way to search for this file. As a workaround, try executing from the top level directory with `cargo run`, and the flag should show.

**Comment by lvella** [comment]
Should be fixed in master now, please test it.

**Comment by alpha-tango-kilo** [comment]
Yep that shows up fine now thanks!
